apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: artifactory-acc
  namespace: artifactory-acc
spec:
  interval: 15m
  timeout: 20m
  chart:
    spec:
      chart: "./charts/acc/artifactory"
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: artifactory-acc
        namespace: flux-system
      valuesFiles:
        - "./charts/acc/artifactory/values.yaml"
        - "./values.acc.yaml"
      interval: 5m
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: ConfigMap
              name: artifactory-acc-configmaps
            patch: |
              - op: replace
                path: /metadata/labels/chart
                value: artifactory-latest

  releaseName: artifactory-acc
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3